name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          # SSH host address.
          host: ${{ secrets.LINODE_HOST }}
          username: gh_deploy
          key: ${{ secrets.LINODE_DEPLOY_KEY }}
          script: /home/gh_deploy/deploy.sh
            
                
