name: Docker Image CI
on:
  workflow_dispatch
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USERNAME: ${{ github.actor }}
  REGISTRY: ghcr.io
  NAMESPACE: ${{ github.actor }}
  IMAGE_NAME: wifi-log-web
  TAG: $(date +%s)
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --target dev --build-arg API_URL=lol --tag ghcr.io/${{ github.actor }}/wifi-log-web:latest
    - name: ghcr login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $REGISTRY -u $USERNAME --password-stdin
    - name: ghrc push
      run: docker push ghcr.io/${{ github.actor }}/wifi-log-web:latest
    
